{{- range .Values.namespaces }}
{{- if .isolated }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ .name }}
  name: isolate-namespace
spec:
  podSelector:
    matchLabels:
  ingress:
  - from:
    - podSelector: {}
{{- end }}
{{- end }}