{{- range .Values.serviceAccounts }}
{{- $saname := .name -}}
{{- range .roleBindings }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ $saname }}-{{ .name }}
  namespace: {{ .namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .kind }}
  name: {{ .name }}
subjects:
- kind: ServiceAccount
  name: {{ $saname }}
  namespace: iam
{{- end }}
{{- end }}
